Script started on Wed 08 Nov 2017 05:54:37 PM PST
]0;cylim1@bondi:~/hw3[cylim1@bondi ~/hw3]$ make clean
rm -f *.o
rm -f PhotoLab
rm -f PhotoLabTest
]0;cylim1@bondi:~/hw3[cylim1@bondi ~/hw3]$ make
gcc -c -Wall -ansi -std=c99 PhotoLab.c -o PhotoLab.o 
gcc -c -Wall -ansi -std=c99 FileIO.c -o FileIO.o
gcc -c -Wall -ansi -std=c99 DIPs.c -o DIPs.o
gcc -c -Wall -ansi -std=c99 Advanced.c -o Advanced.o
ar rc libFilter.a DIPs.o Advanced.o
ranlib libFilter.a
gcc PhotoLab.o FileIO.o -L. -lFilter -o PhotoLab -lm
gcc -c -Wall -ansi -std=c99 PhotoLab.c -o PhotoLabTest.o 
gcc -g PhotoLabTest.o FileIO.o -L. -lFilter -o PhotoLabTest -lm -DDEBUG
]0;cylim1@bondi:~/hw3[cylim1@bondi ~/hw3]$ /[K./Photl[KLa==[K[K[K[KoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
Please make your choice: 15
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
HSSOE.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
HSSOE.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
border.ppm was saved. 
border.jpg was stored.
HSSOE.ppm was read.
noise.ppm was saved. 
noise.jpg was stored.
HSSOE.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
HSSOE.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
Please make your choice: 16
You exit the program.
]0;cylim1@bondi:~/hw3[cylim1@bondi ~/hw3]$ ./PhotoLab[23Gmake[K./PhotoLab[23Gmake[K Photot[KLabTest
make: `PhotoLabTest' is up to date.
]0;cylim1@bondi:~/hw3[cylim1@bondi ~/hw3]$ ./Po[KhotoLabTest

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
Please make your choice: 15
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
HSSOE.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
HSSOE.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
border.ppm was saved. 
border.jpg was stored.
HSSOE.ppm was read.
noise.ppm was saved. 
noise.jpg was stored.
HSSOE.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
HSSOE.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add noise to an image
12: Sharpen an image
13: Posterize an image
14: Motion Blur
15: Test all functions
16: Exit
Please make your choice: 15 6
You exit the program.
]0;cylim1@bondi:~/hw3[cylim1@bondi ~/hw3]$ touch Av[Kdvanced.c
]0;cylim1@bondi:~/hw3[cylim1@bondi ~/hw3]$ make PhotoLab
gcc -c -Wall -ansi -std=c99 Advanced.c -o Advanced.o
ar rc libFilter.a DIPs.o Advanced.o
ranlib libFilter.a
gcc PhotoLab.o FileIO.o -L. -lFilter -o PhotoLab -lm
]0;cylim1@bondi:~/hw3[cylim1@bondi ~/hw3]$ exit
exit

Script done on Wed 08 Nov 2017 05:56:02 PM PST
